### ISSUE TITLE
Chrome does not update CSS edit

### ISSUE THREAD

**Issue by dreadsoul** [tapio/live-server#269]
### The changes in .html are registered and updated. But i am having problems with .css file. The changes in .css file are registered but not updated in Chrome. Can anyone help me please.

**Note**: with Firefox i do not have this problem. 

Here is error in DevTool:
_Console_:
`(index):53 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at refreshCSS (http://127.0.0.1:8080/:53:11)
    at WebSocket.socket.onmessage (http://127.0.0.1:8080/:67:40)
refreshCSS @ (index):53
socket.onmessage @ (index):67`

**more details:**
`
<script type="text/javascript">
	// <![CDATA[  <-- For SVG support
	if ('WebSocket' in window) {
		(function() {
			function refreshCSS() {
				var sheets = [].slice.call(document.getElementsByTagName("link"));
				var head = document.getElementsByTagName("head")[0];
				for (var i = 0; i < sheets.length; ++i) {
					var elem = sheets[i];
					head.removeChild(elem);
					var rel = elem.rel;
					if (elem.href && typeof rel != "string" || rel.length == 0 || rel.toLowerCase() == "stylesheet") {
						var url = elem.href.replace(/(&|\?)_cacheOverride=\d+/, '');
						elem.href = url + (url.indexOf('?') >= 0 ? '&' : '?') + '_cacheOverride=' + (new Date().valueOf());
					}
					head.appendChild(elem);
				}
			}
			var protocol = window.location.protocol === 'http:' ? 'ws://' : 'wss://';
			var address = protocol + window.location.host + window.location.pathname + '/ws';
			var socket = new WebSocket(address);
			socket.onmessage = function(msg) {
				if (msg.data == 'reload') window.location.reload();
				else if (msg.data == 'refreshcss') refreshCSS();
			};
			console.log('Live reload enabled.');
		})();
	}
	// ]]>
</script>`

**Comment by murbar** [comment]
Same problem here. Seems to work fine in Safari.

**Comment by blessochampion** [comment]
This has been fixed here https://github.com/tapio/live-server/pull/283/commits/db9f12ddecbd5887e0110fff3d5820069a274c20 , but I do not know why it is not part of the master build.

To install this particular fix, do the following:

` npm install -g "git+https://github.com/tapio/live-server.git#db9f12ddecbd5887e0110fff3d5820069a274c20"`

**Comment by CharidimosTzedakis** [comment]
I face the same problem on Chrome Version 75.0.3770.142 (Official Build) (64-bit)
The pull request of this https://github.com/tapio/live-server/commit/db9f12ddecbd5887e0110fff3d5820069a274c20 is still open: https://github.com/tapio/live-server/pull/283

It seems that the CI pipeline failed, and now it has also conflicts that need to be resolved.

**Comment by FrancescoMagliocco** [comment]
> I face the same problem on Chrome Version 75.0.3770.142 (Official Build) (64-bit)
> The pull request of this [db9f12d](https://github.com/tapio/live-server/commit/db9f12ddecbd5887e0110fff3d5820069a274c20) is still open: #283
> 
> It seems that the CI pipeline failed.
> 
> Alternatively, you can use:
> `live-server --no-css-inject`

Using the `--no-css-inject` flag still does not work for me.

My node version is v12.8.0
